// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxFNaVWobtdpoGh50w4zTeiaiUUBY3jIM',
    appId: '1:1084009091410:web:3944d7f65a27022d47aa8b',
    messagingSenderId: '1084009091410',
    projectId: 'twitterclone-4ead6',
    authDomain: 'twitterclone-4ead6.firebaseapp.com',
    storageBucket: 'twitterclone-4ead6.appspot.com',
    measurementId: 'G-XGV9BT4ZRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhN6tdcilToGCSyUnoeb9RldmgI-eKSbE',
    appId: '1:1084009091410:android:62446b7b11ce0f5447aa8b',
    messagingSenderId: '1084009091410',
    projectId: 'twitterclone-4ead6',
    storageBucket: 'twitterclone-4ead6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-MsWS9JdNvXZM7PNGjF7Bh8lvnK1lO-M',
    appId: '1:1084009091410:ios:4b00ed44fb956eaa47aa8b',
    messagingSenderId: '1084009091410',
    projectId: 'twitterclone-4ead6',
    storageBucket: 'twitterclone-4ead6.appspot.com',
    iosClientId: '1084009091410-btd3q407l6178cj887bua9o4v9s2bg3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.twclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-MsWS9JdNvXZM7PNGjF7Bh8lvnK1lO-M',
    appId: '1:1084009091410:ios:4b00ed44fb956eaa47aa8b',
    messagingSenderId: '1084009091410',
    projectId: 'twitterclone-4ead6',
    storageBucket: 'twitterclone-4ead6.appspot.com',
    iosClientId: '1084009091410-btd3q407l6178cj887bua9o4v9s2bg3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.twclone',
  );
}
